FROM python:3.12

WORKDIR /app
COPY requirements.txt ./
# install dependencies
RUN pip install --no-cache-dir -r ./requirements.txt

COPY service/ ./service

WORKDIR ./service

# set environment variables
ENV FLASK_APP=service
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=8000

# to inform users (or automated tools) that this application
# is intended to run on port 8000 inside the container
EXPOSE 8000

CMD ["flask", "run"]
